services:
  # web:
  #   build: .
  #   container_name: db-final-backend
  #   ports:
  #     - "3010:3010"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     mongo:
  #       condition: service_healthy
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     POSTGRES_HOST: 'db'
  #     POSTGRES_PORT: '5432'
  #     POSTGRES_DB_NAME: 'postgres'
  #     POSTGRES_USER: 'postgres'
  #     POSTGRES_PASSWORD: 'dbfinal'
  #     PORT: '3010'
  #     FRONTEND_URL: 'http://localhost:3000'
  #     MONGO_HOST: 'mongo'
  #     MONGO_PORT: '27017'
  #     MONGO_USER: 'root'
  #     MONGO_PASSWORD: 'dbfinal'
  #     MONGO_DB_NAME: 'jojo'
 
  db:
    container_name: db-fianl-pg
    image: postgres:18.1
    restart: always
    ports:
      - "23013:5432"
    environment:
      POSTGRES_PASSWORD: dbfinal
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    # volumes:
    #   - ./db/data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  mongo:
    container_name: db-final-mongo
    image: mongo:8.2.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbfinal
    volumes:
      - ./db/mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
